services:
  disneyplus-otp-forwarder:
    build: .
    container_name: disneyplus-otp-forwarder
    volumes:
      - ./app.js:/usr/src/app/app.js
    env_file:
      - .env
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"